// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfy59IlXRgV2AhxRSpisKrDKvxgES3r8o',
    appId: '1:1095274966890:web:9e7f19ab0533b45bfeff13',
    messagingSenderId: '1095274966890',
    projectId: 'beninpoulet-8f04a',
    authDomain: 'beninpoulet-8f04a.firebaseapp.com',
    storageBucket: 'beninpoulet-8f04a.firebasestorage.app',
    measurementId: 'G-X2XGRFP6SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ52clxdKdy8wtn-jzPQVsUNZ1ejllKZA',
    appId: '1:1095274966890:android:bf9ef0ca7954fd97feff13',
    messagingSenderId: '1095274966890',
    projectId: 'beninpoulet-8f04a',
    storageBucket: 'beninpoulet-8f04a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfQQHJzO3tkRR1mlHmCD4ksSfweCA3AqY',
    appId: '1:1095274966890:ios:f5332d7ba940d851feff13',
    messagingSenderId: '1095274966890',
    projectId: 'beninpoulet-8f04a',
    storageBucket: 'beninpoulet-8f04a.firebasestorage.app',
    iosBundleId: 'com.codeurplus.beninPoulet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfQQHJzO3tkRR1mlHmCD4ksSfweCA3AqY',
    appId: '1:1095274966890:ios:f5332d7ba940d851feff13',
    messagingSenderId: '1095274966890',
    projectId: 'beninpoulet-8f04a',
    storageBucket: 'beninpoulet-8f04a.firebasestorage.app',
    iosBundleId: 'com.codeurplus.beninPoulet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfy59IlXRgV2AhxRSpisKrDKvxgES3r8o',
    appId: '1:1095274966890:web:f80777da02b1bd37feff13',
    messagingSenderId: '1095274966890',
    projectId: 'beninpoulet-8f04a',
    authDomain: 'beninpoulet-8f04a.firebaseapp.com',
    storageBucket: 'beninpoulet-8f04a.firebasestorage.app',
    measurementId: 'G-RR231PVTP5',
  );
}
